name: Auto merge templates

on:
  pull_request:
    paths:
      - "templates/**/**/*.json"

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true
